# Generated by Django 6.1 on 2026-08-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(db_column='DepartmentID', primary_key=True, serialize=False)),
                ('department_code', models.CharField(db_column='DepartmentCode', max_length=50, unique=True)),
                ('department_name', models.CharField(db_column='DepartmentName', max_length=150)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role_code', models.CharField(db_column='RoleCode', max_length=50, unique=True)),
                ('role_name', models.CharField(db_column='RoleName', max_length=100)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('employee_id', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('employee_code', models.CharField(db_column='EmployeeCode', max_length=50, unique=True)),
                ('first_name', models.CharField(db_column='FirstName', max_length=100)),
                ('last_name', models.CharField(db_column='LastName', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=150, unique=True)),
                ('ad_username', models.CharField(blank=True, db_column='ADUsername', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('department', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='authentication.department')),
            ],
            options={
                'verbose_name': 'Employee Master',
                'verbose_name_plural': 'Employee Masters',
                'db_table': 'EmployeeMaster',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=100, unique=True)),
                ('email', models.EmailField(db_column='Email', max_length=150, unique=True)),
                ('auth_mode', models.CharField(choices=[('LOCAL', 'Local Database Authentication'), ('AD', 'Active Directory Authentication')], db_column='AuthMode', default='LOCAL', max_length=10)),
                ('password_hash', models.CharField(blank=True, db_column='PasswordHash', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('last_login_at', models.DateTimeField(blank=True, db_column='LastLoginAt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('employee', models.OneToOneField(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, related_name='system_user', to='authentication.employeemaster')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'db_table': 'SystemUser',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(db_column='UserRoleID', primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_column='AssignedAt')),
                ('assigned_by', models.ForeignKey(blank=True, db_column='AssignedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to='authentication.systemuser')),
                ('role', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='authentication.role')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='authentication.systemuser')),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'db_table': 'UserRole',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
