# Generated by Django 6.1 on 2026-08-18 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentApproverConfiguration',
            fields=[
                ('config_id', models.AutoField(db_column='ConfigID', primary_key=True, serialize=False)),
                ('approver_mode', models.CharField(choices=[('MANUAL', 'Manual Pre-configured Approvers'), ('DYNAMIC', 'Dynamic Buyer Selected Approvers')], db_column='ApproverMode', default='DYNAMIC', max_length=20)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('created_by', models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dept_configs', to='authentication.systemuser')),
                ('department', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.CASCADE, related_name='approver_configs', to='authentication.department')),
            ],
            options={
                'verbose_name': 'Department Approver Configuration',
                'verbose_name_plural': 'Department Approver Configurations',
                'db_table': 'DepartmentApproverConfiguration',
            },
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('error_id', models.AutoField(db_column='ErrorID', primary_key=True, serialize=False)),
                ('error_source', models.CharField(db_column='ErrorSource', default='BACKEND_API', max_length=100)),
                ('exception_type', models.CharField(db_column='ExceptionType', max_length=150)),
                ('error_message', models.TextField(db_column='ErrorMessage')),
                ('stack_trace', models.TextField(db_column='StackTrace')),
                ('endpoint', models.CharField(blank=True, db_column='Endpoint', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='authentication.systemuser')),
            ],
            options={
                'verbose_name': 'System Error Log',
                'verbose_name_plural': 'System Error Logs',
                'db_table': 'SystemErrorLog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConfiguration',
            fields=[
                ('workflow_config_id', models.AutoField(db_column='WorkflowConfigID', primary_key=True, serialize=False)),
                ('return_mode', models.CharField(choices=[('RETURN_TO_INITIATOR', 'Return to Initiator (Buyer)'), ('RETURN_TO_PREVIOUS_APPROVER', 'Return to Previous Approver')], db_column='ReturnMode', default='RETURN_TO_INITIATOR', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('config', models.OneToOneField(db_column='ConfigID', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_config', to='authentication.departmentapproverconfiguration')),
            ],
            options={
                'verbose_name': 'Workflow Return Configuration',
                'verbose_name_plural': 'Workflow Return Configurations',
                'db_table': 'WorkflowConfiguration',
            },
        ),
        migrations.CreateModel(
            name='ManualApproverConfiguration',
            fields=[
                ('manual_config_id', models.AutoField(db_column='ManualConfigID', primary_key=True, serialize=False)),
                ('approver_level', models.IntegerField(db_column='ApproverLevel')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('approver_user', models.ForeignKey(db_column='ApproverUserID', on_delete=django.db.models.deletion.CASCADE, related_name='manual_approver_assignments', to='authentication.systemuser')),
                ('config', models.ForeignKey(db_column='ConfigID', on_delete=django.db.models.deletion.CASCADE, related_name='manual_approvers', to='authentication.departmentapproverconfiguration')),
            ],
            options={
                'verbose_name': 'Manual Approver Sequence',
                'verbose_name_plural': 'Manual Approver Sequences',
                'db_table': 'ManualApproverConfiguration',
                'ordering': ['approver_level'],
                'unique_together': {('config', 'approver_level')},
            },
        ),
    ]
