# Generated by Django 6.1 on 2026-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_departmentapproverconfiguration_systemerrorlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('config_id', models.AutoField(db_column='ConfigID', primary_key=True, serialize=False)),
                ('setting_key', models.CharField(db_column='SettingKey', max_length=100, unique=True)),
                ('setting_value', models.CharField(db_column='SettingValue', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
                'db_table': 'SystemConfiguration',
            },
        ),
    ]
