# Generated by Django 6.1 on 2026-08-18 10:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_systemconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFARequest',
            fields=[
                ('nfa_request_id', models.UUIDField(db_column='NFARequestID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nfa_number', models.CharField(db_column='NFANumber', max_length=50, unique=True)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=150)),
                ('business_justification', models.TextField(db_column='BusinessJustification')),
                ('commercial_impact', models.TextField(db_column='CommercialImpact')),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=15)),
                ('vendor_name', models.CharField(blank=True, db_column='VendorName', max_length=200, null=True)),
                ('current_status', models.CharField(choices=[('DRAFT', 'Draft (Editable)'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Fully Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned for Clarification')], db_column='CurrentStatus', default='DRAFT', max_length=30)),
                ('current_level', models.IntegerField(db_column='CurrentLevel', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('buyer', models.ForeignKey(db_column='BuyerID', on_delete=django.db.models.deletion.PROTECT, related_name='created_nfa_requests', to='authentication.systemuser')),
                ('department', models.ForeignKey(db_column='DepartmentID', on_delete=django.db.models.deletion.PROTECT, related_name='nfa_requests', to='authentication.department')),
            ],
            options={
                'verbose_name': 'NFA Request',
                'verbose_name_plural': 'NFA Requests',
                'db_table': 'NFARequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFAApprovalHistory',
            fields=[
                ('history_id', models.AutoField(db_column='HistoryID', primary_key=True, serialize=False)),
                ('action_type', models.CharField(db_column='ActionType', max_length=50)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('action_at', models.DateTimeField(auto_now_add=True, db_column='ActionAt')),
                ('action_by', models.ForeignKey(db_column='ActionByID', on_delete=django.db.models.deletion.PROTECT, related_name='nfa_actions', to='authentication.systemuser')),
                ('nfa_request', models.ForeignKey(db_column='NFARequestID', on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='authentication.nfarequest')),
            ],
            options={
                'verbose_name': 'NFA Approval History Audit Log',
                'verbose_name_plural': 'NFA Approval History Audit Logs',
                'db_table': 'NFAApprovalHistory',
                'ordering': ['action_at'],
            },
        ),
        migrations.CreateModel(
            name='NFARequestVersion',
            fields=[
                ('nfa_version_id', models.UUIDField(db_column='NFAVersionID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(db_column='VersionNumber', default=1)),
                ('snapshot_data', models.JSONField(db_column='SnapshotData')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('nfa_request', models.ForeignKey(db_column='NFARequestID', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='authentication.nfarequest')),
            ],
            options={
                'verbose_name': 'NFA Request Version Snapshot',
                'verbose_name_plural': 'NFA Request Version Snapshots',
                'db_table': 'NFARequestVersion',
                'ordering': ['version_number'],
                'unique_together': {('nfa_request', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='NFAAttachment',
            fields=[
                ('attachment_id', models.AutoField(db_column='AttachmentID', primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(db_column='VersionNumber', default=1)),
                ('file_name', models.CharField(db_column='FileName', max_length=255)),
                ('file_path', models.CharField(db_column='FilePath', max_length=500)),
                ('file_size', models.BigIntegerField(db_column='FileSize')),
                ('content_type', models.CharField(db_column='ContentType', max_length=100)),
                ('is_deleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='UploadedAt')),
                ('nfa_request', models.ForeignKey(db_column='NFARequestID', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='authentication.nfarequest')),
                ('nfa_version', models.ForeignKey(blank=True, db_column='NFAVersionID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_attachments', to='authentication.nfarequestversion')),
            ],
            options={
                'verbose_name': 'NFA File Attachment',
                'verbose_name_plural': 'NFA File Attachments',
                'db_table': 'NFAAttachment',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
