# Generated by Django 6.1 on 2026-08-19 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_nfarequest_nfaapprovalhistory_nfarequestversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('template_id', models.UUIDField(db_column='TemplateID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_column='EventType', max_length=50, unique=True)),
                ('event_description', models.CharField(db_column='EventDescription', max_length=255)),
                ('email_subject', models.CharField(db_column='EmailSubject', max_length=255)),
                ('html_body', models.TextField(db_column='HtmlBody')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
            ],
            options={
                'db_table': 'NotificationTemplates',
            },
        ),
    ]
